# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_sum_of_minima_triangle <- function(n, index, inner_terms) {
    .Call(`_tame_rcpp_sum_of_minima_triangle`, n, index, inner_terms)
}

rcpp_sum_of_minima_full <- function(n, m, row_index, col_index, inner_terms) {
    .Call(`_tame_rcpp_sum_of_minima_full`, n, m, row_index, col_index, inner_terms)
}

rcpp_double_sum_triangle <- function(n, index, inner_terms) {
    .Call(`_tame_rcpp_double_sum_triangle`, n, index, inner_terms)
}

rcpp_double_sum_full <- function(n, m, row_index, col_index, inner_terms) {
    .Call(`_tame_rcpp_double_sum_full`, n, m, row_index, col_index, inner_terms)
}

